config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root   'static_pages#home'
  get    '/help',     to: 'static_pages#help'
  get    '/about',    to: 'static_pages#about'
  get    '/contact',  to: 'static_pages#contact'
  get    '/settings', to: 'static_pages#settings'
  get    '/signup',   to: 'users#new'
  post   '/signup',   to: 'users#create'
  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'
  resources :users
  resources :transactions
  resources :categories, only: :index
  resources :groups, only: [:new, :create, :edit, :update]
  resources :sources, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :analysis, only: :show
end

app/models/user.rb
class User < ApplicationRecord
  has_many :transactions, dependent: :destroy do
    def source(flag)
      case flag
      when :all then self
      when :hide then not_nae.not_central
      when :central then central
      else self
      end
    end

    def not_central_if(flag)
      flag ? not_central : self
    end
  end
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  class << self
    # 渡された文字列のハッシュ値を返す
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
    
    # ランダムなトークンを返す
    def new_token
      SecureRandom.urlsafe_base64
    end
  end
  
  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # トークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # アカウントを有効にする
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest:  User.digest(reset_token),
                   reset_sent_at: Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  private

    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email.downcase!
    end

    # 有効化トークンとダイジェストを作成および代入する
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  
  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    redirect_to root_url and return unless @user.activated?
    @q = @user.transactions.ransack(params[:q])

    # デフォルトでは有効データだけを表示
    @q.valid_record_true = 'true' unless params[:q]

    @transactions = @q.result.paginate(page: params[:page]).order(created_at: "DESC", id: "ASC")
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def edit
    p 'edit'
    @user = User.find(params[:id])
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
  
    # beforeアクション

    # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:url)) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:url, user_path) %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:url, signup_path) %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="col-md-12">
    <%= button_to 'add', new_transaction_path, method: :get, class: "btn btn-primary btn-sm", params: { date: @transactions.first&.created_at } %>
    <%= search_form_for @q, url: @user do |f| %>
      <ul class="search_form">
        <li>
          <span class="timestamp">
            <%= f.label :created_at_gteq_beginning_of_day, 'date:' %>
            <%= f.search_field :created_at_gteq_beginning_of_day, data: { date_format: 'YYYY/MM/DD' }, class: 'date_picker_start', placeholder: 'YYYY/MM/DD', autocomplete: 'off' %>

            <%= f.label :created_at_lteq_end_of_day, '〜' %>
            <%= f.search_field :created_at_lteq_end_of_day, data: { date_format: 'YYYY/MM/DD' }, class: 'date_picker_end', placeholder: 'YYYY/MM/DD', autocomplete: 'off' %>
          </span>
          /
          <span class="content">
            <%= f.label :content_or_memo_cont, 'content:' %>
            <%= f.search_field :content_or_memo_cont %>
          </span>
          /
          <span class="yen">
            <%= f.label :yen_eq, 'yen:' %>
            <%= f.search_field :yen_eq %>
          </span>
        </li>

        <li>
          <span class="category">
            <%= f.label :category_id_eq, 'category:' %>
            <%= f.collection_select :category_id_eq, Category.where(parent: nil), :id, :name, include_blank: true %>
          </span>
          <span class="genre">
            <%= f.collection_select :category_id_eq, Category.all, :id, :name, include_blank: true %>
          </span>
          /
          <span class="store">
            <%= f.label :store_name_cont, 'store:' %>
            <%= f.search_field :store_name_cont %>
          </span>
          /
          <span class="source">
            <%= f.label :source_id_eq, 'source:' %>
            <%= f.collection_select :source_id_eq, Source.all, :id, :name, include_blank: true %>
          </span>
          /
          <span class="group">
            <%= f.label :group_id_eq, 'group:' %>
            <%= f.collection_select :group_id_eq, Group.all, :id, :name, include_blank: true %>
          </span>
        </li>

        <li>
          <span class="valid_record">
            <%= f.label :valid_record_true, 'valid:' %>
            <%= f.check_box :valid_record_true, {}, checked_value = 'true', unchecked_value = '' %>
          </span>
        </li>

        <li>
          <%= f.submit %>
        </li>
      </ul>
    <% end %>
    <% if @transactions.any? %>
      <h3>Transactions (<%= @transactions.count %>件) 計<%= @transactions.sum(:yen) %>円</h3>
      <ol class="transactions">
        <%= render @transactions %>
      </ol>
      <%= will_paginate @transactions %>
    <% end %>
  </div>
</div>